[workspace]
resolver = "2"
members = [
  "comprehensive",
  "comprehensive_dns",
  "comprehensive_grpc",
  "comprehensive_http",
  "comprehensive_macros",
  "comprehensive_s3",
  "comprehensive_traits",
  "comprehensive_warm_channels",
  "examples",
]
